<a href="https://colab.research.google.com/github/kasicharan234-hub/EDA/blob/main/25bai0028Eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("bank_marketing_test.csv")

In [16]:
print(df.head())

   age          job  marital    education  default housing loan    contact  \
0   56     services  married  high.school       no      no  yes  telephone
1   41  blue-collar  married      unknown  unknown      no   no  telephone
2   25     services   single  high.school       no     yes   no  telephone
3   35  blue-collar  married     basic.6y       no     yes   no  telephone
4   46  blue-collar  married     basic.6y  unknown     yes  yes  telephone

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1
1   may         mon  ...         1    999         0  nonexistent          1.1
2   may         mon  ...         1    999         0  nonexistent          1.1
3   may         mon  ...         1    999         0  nonexistent          1.1
4   may         mon  ...         1    999         0  nonexistent          1.1

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y
0          93.994          -36.4      4.857       5191.0  no
1          93.994          -36.4      4.857       5191.0  no
2          93.994          -36.4      4.857       5191.0  no
3          93.994          -36.4      4.857       5191.0  no
4          93.994          -36.4      4.857       5191.0  no

[5 rows x 21 columns]

In [17]:
print(df.tail())

      age          job  marital          education default housing loan  \
8232   41  blue-collar  married           basic.9y      no     yes   no
8233   60  blue-collar  married           basic.4y      no     yes   no
8234   32       admin.  married  university.degree      no      no   no
8235   32       admin.  married  university.degree      no     yes   no
8236   36       admin.  married  university.degree      no      no   no

        contact month day_of_week  ...  campaign  pdays  previous  \
8232   cellular   nov         mon  ...         2    999         1
8233   cellular   nov         tue  ...         2      4         1
8234  telephone   nov         wed  ...         1    999         1
8235   cellular   nov         wed  ...         3    999         0
8236   cellular   nov         fri  ...         2    999         0

         poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
8232      failure         -1.1          94.767          -50.8      1.039
8233      success         -1.1          94.767          -50.8      1.035
8234      failure         -1.1          94.767          -50.8      1.030
8235  nonexistent         -1.1          94.767          -50.8      1.030
8236  nonexistent         -1.1          94.767          -50.8      1.028

      nr.employed    y
8232       4963.6   no
8233       4963.6   no
8234       4963.6  yes
8235       4963.6   no
8236       4963.6   no

[5 rows x 21 columns]

In [18]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8237 entries, 0 to 8236
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             8237 non-null   int64
 1   job             8237 non-null   object
 2   marital         8237 non-null   object
 3   education       8237 non-null   object
 4   default         8237 non-null   object
 5   housing         8237 non-null   object
 6   loan            8237 non-null   object
 7   contact         8237 non-null   object
 8   month           8237 non-null   object
 9   day_of_week     8237 non-null   object
 10  duration        8237 non-null   int64
 11  campaign        8237 non-null   int64
 12  pdays           8237 non-null   int64
 13  previous        8237 non-null   int64
 14  poutcome        8237 non-null   object
 15  emp.var.rate    8237 non-null   float64
 16  cons.price.idx  8237 non-null   float64
 17  cons.conf.idx   8237 non-null   float64
 18  euribor3m       8237 non-null   float64
 19  nr.employed     8237 non-null   float64
 20  y               8237 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 1.3+ MB
None

In [19]:
print(df.shape)

(8237, 21)

In [20]:
print(df.columns)

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [21]:
print(df.describe())

               age     duration    campaign        pdays     previous  \
count  8237.000000  8237.000000  8237.00000  8237.000000  8237.000000
mean     40.116547   256.007648     2.60471   962.228724     0.174335
std      10.465328   259.728737     2.91562   187.533881     0.500565
min      17.000000     4.000000     1.00000     0.000000     0.000000
25%      32.000000   101.000000     1.00000   999.000000     0.000000
50%      38.000000   179.000000     2.00000   999.000000     0.000000
75%      47.000000   316.000000     3.00000   999.000000     0.000000
max      89.000000  4918.000000    43.00000   999.000000     6.000000

       emp.var.rate  cons.price.idx  cons.conf.idx    euribor3m  nr.employed
count   8237.000000     8237.000000    8237.000000  8237.000000  8237.000000
mean       0.070147       93.577806     -40.545320     3.608206  5166.589790
std        1.574685        0.582138       4.623626     1.735931    72.470977
min       -3.400000       92.201000     -50.800000     0.634000  4963.600000
25%       -1.800000       93.075000     -42.700000     1.344000  5099.100000
50%        1.100000       93.444000     -41.800000     4.857000  5191.000000
75%        1.400000       93.994000     -36.400000     4.961000  5228.100000
max        1.400000       94.767000     -26.900000     5.000000  5228.100000

In [22]:
df.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8237 entries, 0 to 8236
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             8237 non-null   int64
 1   job             8237 non-null   object
 2   marital         8237 non-null   object
 3   education       8237 non-null   object
 4   default         8237 non-null   object
 5   housing         8237 non-null   object
 6   loan            8237 non-null   object
 7   contact         8237 non-null   object
 8   month           8237 non-null   object
 9   day_of_week     8237 non-null   object
 10  duration        8237 non-null   int64
 11  campaign        8237 non-null   int64
 12  pdays           8237 non-null   int64
 13  previous        8237 non-null   int64
 14  poutcome        8237 non-null   object
 15  emp.var.rate    8237 non-null   float64
 16  cons.price.idx  8237 non-null   float64
 17  cons.conf.idx   8237 non-null   float64
 18  euribor3m       8237 non-null   float64
 19  nr.employed     8237 non-null   float64
 20  y               8237 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 1.3+ MB

In [24]:
df["age"]

0       56
1       41
2       25
3       35
4       46
        ..
8232    41
8233    60
8234    32
8235    32
8236    36
Name: age, Length: 8237, dtype: int64

In [25]:
df[["age", "cons.price.idx"]]

      age  cons.price.idx
0      56          93.994
1      41          93.994
2      25          93.994
3      35          93.994
4      46          93.994
...   ...             ...
8232   41          94.767
8233   60          94.767
8234   32          94.767
8235   32          94.767
8236   36          94.767

[8237 rows x 2 columns]

In [26]:
df.iloc[0]

age                        56
job                  services
marital               married
education         high.school
default                    no
housing                    no
loan                      yes
contact             telephone
month                     may
day_of_week               mon
duration                  307
campaign                    1
pdays                     999
previous                    0
poutcome          nonexistent
emp.var.rate              1.1
cons.price.idx         93.994
cons.conf.idx           -36.4
euribor3m               4.857
nr.employed            5191.0
y                          no
Name: 0, dtype: object

In [27]:
df.iloc[1:5]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [28]:
df.isnull()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8232,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8233,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8234,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8235,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8236,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [29]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [30]:
df.dropna()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no

In [31]:
df.fillna(0)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no

In [32]:
df["age"].unique()

array([56, 41, 25, 35, 46, 55, 40, 45, 53, 42, 51, 38, 60, 33, 44, 37, 50,
       52, 36, 39, 43, 34, 30, 32, 28, 54, 58, 26, 49, 57, 59, 48, 47, 27,
       31, 29, 24, 22, 20, 21, 23, 18, 70, 76, 88, 66, 72, 61, 63, 82, 69,
       19, 68, 73, 75, 78, 64, 85, 77, 65, 83, 62, 17, 67, 74, 71, 87, 80,
       81, 86, 79, 89])

In [33]:
df["age"].value_counts()

age
32    389
31    380
33    366
36    359
34    347
     ...
79      2
86      2
17      1
87      1
89      1
Name: count, Length: 72, dtype: int64

In [34]:
df[df["age"] > 80]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
5530,88,retired,divorced,basic.4y,no,yes,yes,cellular,mar,wed,...,5,999,0,nonexistent,-1.8,92.843,-50.0,1.663,5099.1,yes
5531,88,retired,divorced,basic.4y,no,yes,no,cellular,mar,wed,...,1,999,0,nonexistent,-1.8,92.843,-50.0,1.663,5099.1,yes
5532,88,retired,divorced,basic.4y,no,no,no,cellular,mar,wed,...,1,999,0,nonexistent,-1.8,92.843,-50.0,1.663,5099.1,yes
5533,88,retired,divorced,basic.4y,no,yes,no,cellular,mar,wed,...,1,999,0,nonexistent,-1.8,92.843,-50.0,1.663,5099.1,no
5534,88,retired,divorced,basic.4y,no,yes,no,cellular,mar,wed,...,1,999,0,nonexistent,-1.8,92.843,-50.0,1.663,5099.1,yes
5628,82,retired,married,unknown,no,no,no,cellular,apr,wed,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.445,5099.1,yes
5998,85,retired,married,basic.4y,no,yes,no,cellular,apr,fri,...,2,999,0,nonexistent,-1.8,93.075,-47.1,1.400,5099.1,no
7161,83,retired,married,basic.9y,no,yes,yes,cellular,may,fri,...,1,3,3,failure,-1.8,92.893,-46.2,1.259,5099.1,no
7233,88,retired,divorced,basic.4y,no,yes,no,cellular,may,wed,...,4,999,0,nonexistent,-1.8,92.893,-46.2,1.270,5099.1,no
7464,85,retired,married,professional.course,no,no,no,cellular,aug,tue,...,1,999,0,nonexistent,-2.9,92.201,-31.4,0.883,5076.2,yes
7540,87,retired,divorced,basic.4y,no,no,no,cellular,aug,fri,...,1,999,0,nonexistent,-2.9,92.201,-31.4,0.849,5076.2,yes
7550,88,retired,married,university.degree,no,yes,no,cellular,aug,mon,...,1,999,0,nonexistent,-2.9,92.201,-31.4,0.843,5076.2,no
7602,83,retired,married,unknown,no,yes,no,cellular,sep,mon,...,2,999,0,nonexistent,-3.4,92.379,-29.8,0.771,5017.5,no
7624,83,retired,married,professional.course,no,yes,no,cellular,oct,fri,...,2,4,1,success,-3.4,92.431,-26.9,0.752,5017.5,yes
7625,82,retired,married,university.degree,no,yes,no,cellular,oct,tue,...,1,999,0,nonexistent,-3.4,92.431,-26.9,0.744,5017.5,yes
7628,82,retired,married,university.degree,no,yes,yes,cellular,oct,tue,...,1,999,1,failure,-3.4,92.431,-26.9,0.744,5017.5,no
7629,82,retired,married,university.degree,no,yes,no,cellular,oct,tue,...,1,999,0,nonexistent,-3.4,92.431,-26.9,0.744,5017.5,no
7697,81,retired,married,university.degree,unknown,yes,yes,cellular,oct,tue,...,2,6,1,success,-3.4,92.431,-26.9,0.728,5017.5,no
7710,82,retired,single,basic.4y,no,yes,no,cellular,oct,thu,...,2,999,0,nonexistent,-3.4,92.431,-26.9,0.722,5017.5,yes
7738,81,unknown,divorced,unknown,unknown,yes,no,cellular,nov,mon,...,1,999,1,failure,-3.4,92.649,-30.1,0.715,5017.5,yes
7788,81,housemaid,divorced,basic.4y,no,yes,no,cellular,nov,mon,...,6,999,0,nonexistent,-3.4,92.649,-30.1,0.719,5017.5,no
7807,85,retired,divorced,basic.4y,unknown,yes,no,telephone,dec,tue,...,1,999,0,nonexistent,-3.0,92.713,-33.0,0.715,5023.5,no
7858,82,retired,married,professional.course,no,yes,no,telephone,mar,mon,...,2,999,0,nonexistent,-1.8,93.369,-34.8,0.646,5008.7,yes
7875,86,retired,married,basic.4y,unknown,yes,no,cellular,mar,tue,...,2,999,2,failure,-1.8,93.369,-34.8,0.635,5008.7,no
7894,85,housemaid,married,basic.4y,unknown,yes,no,cellular,apr,tue,...,1,6,2,success,-1.8,93.749,-34.6,0.642,5008.7,yes
7961,89,retired,divorced,basic.4y,no,no,no,cellular,jun,mon,...,1,999,0,nonexistent,-1.7,94.055,-39.8,0.720,4991.6,yes
8112,81,retired,divorced,basic.4y,no,no,no,cellular,sep,wed,...,2,7,1,success,-1.1,94.199,-37.5,0.886,4963.6,yes
8125,88,retired,married,basic.4y,no,yes,no,cellular,sep,mon,...,7,999,0,nonexistent,-1.1,94.199,-37.5,0.882,4963.6,no
8138,83,retired,divorced,basic.4y,no,no,no,cellular,sep,thu,...,1,9,3,success,-1.1,94.199,-37.5,0.879,4963.6,yes
8145,86,retired,married,unknown,unknown,yes,yes,cellular,sep,tue,...,1,7,4,success,-1.1,94.199,-37.5,0.877,4963.6,yes

In [35]:
df["age"].max()

89

In [36]:
df["age"].min()

17

In [37]:
df["age"].mean()

np.float64(40.116547286633484)

In [38]:
df["age"].sum()

np.int64(330440)

In [39]:
df["age"].nunique()

72

In [40]:
df.rename(columns={"job": "occupation"})

,age,occupation,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no