<a href="https://colab.research.google.com/github/kasicharan234-hub/EDA/blob/main/experiment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1Car =  pd.DataFrame({ 'VehicleID': [101, 103, 105, 107, 109, 111, 113, 115, 117, 119],
                       'parkingFeeC' : [40, 60, 50, 80, 30, 70, 90, 45, 55, 65]})
df2Car =  pd.DataFrame({'VehicleID': [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
                       'parkingFeeC': [ 35, 75, 50, 60, 45, 55, 65, 70, 80, 40]})
df1Bike =  pd.DataFrame({ 'VehicleID': [101, 103, 105, 107, 109, 111, 113, 115, 117,119],
                       'parkingFeeB' : [20, 25, 15, 30, 20, 35, 25, 30, 15, 20]})
df2Bike =  pd.DataFrame({'VehicleID': [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
                       'parkingFeeB': [15, 20, 25, 20, 30, 25, 35, 15, 20, 30]})

In [ ]:
dfCar = pd.concat([df1Car, df2Car], ignore_index=True)
dfBike = pd.concat([df1Bike, df2Bike], ignore_index=True)

df = pd.concat([dfBike, dfCar], axis=1)
df

    VehicleID  parkingFeeB  VehicleID  parkingFeeC
0         101           20        101           40
1         103           25        103           60
2         105           15        105           50
3         107           30        107           80
4         109           20        109           30
5         111           35        111           70
6         113           25        113           90
7         115           30        115           45
8         117           15        117           55
9         119           20        119           65
10        102           15        102           35
11        104           20        104           75
12        106           25        106           50
13        108           20        108           60
14        110           30        110           45
15        112           25        112           55
16        114           35        114           65
17        116           15        116           70
18        118           20        118           80
19        120           30        120           40

In [ ]:
dfCar = pd.concat([df1Car, df2Car], ignore_index=True)
dfBike = pd.concat([df1Bike, df2Bike], ignore_index=True)

df = dfCar.merge(dfBike, how='inner')
df

    VehicleID  parkingFeeC  parkingFeeB
0         101           40           20
1         103           60           25
2         105           50           15
3         107           80           30
4         109           30           20
5         111           70           35
6         113           90           25
7         115           45           30
8         117           55           15
9         119           65           20
10        102           35           15
11        104           75           20
12        106           50           25
13        108           60           20
14        110           45           30
15        112           55           25
16        114           65           35
17        116           70           15
18        118           80           20
19        120           40           30

In [ ]:
dfCar = pd.concat([df1Car, df2Car], ignore_index=True)
dfBike = pd.concat([df1Bike, df2Bike], ignore_index=True)

df = dfCar.merge(dfBike, how='left')
df

    VehicleID  parkingFeeC  parkingFeeB
0         101           40           20
1         103           60           25
2         105           50           15
3         107           80           30
4         109           30           20
5         111           70           35
6         113           90           25
7         115           45           30
8         117           55           15
9         119           65           20
10        102           35           15
11        104           75           20
12        106           50           25
13        108           60           20
14        110           45           30
15        112           55           25
16        114           65           35
17        116           70           15
18        118           80           20
19        120           40           30

In [ ]:
dfCar = pd.concat([df1Car, df2Bike], ignore_index=True)
dfBike = pd.concat([df1Bike, df2Bike], ignore_index=True)

df = dfCar.merge(dfBike, how='right')
df

    VehicleID  parkingFeeC  parkingFeeB
0         101          NaN         20.0
1         103          NaN         25.0
2         105          NaN         15.0
3         107          NaN         30.0
4         109          NaN         20.0
5         111          NaN         35.0
6         113          NaN         25.0
7         115          NaN         30.0
8         117          NaN         15.0
9         119          NaN         20.0
10        102          NaN         15.0
11        104          NaN         20.0
12        106          NaN         25.0
13        108          NaN         20.0
14        110          NaN         30.0
15        112          NaN         25.0
16        114          NaN         35.0
17        116          NaN         15.0
18        118          NaN         20.0
19        120          NaN         30.0