<a href="https://colab.research.google.com/github/kasicharan234-hub/EDA/blob/main/experiment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
height = [120, 122, 125, 127, 121, 123, 137, 131, 161, 145, 141, 132]
bins = [118, 125, 135, 160, 200]
category = pd.cut(height, bins)
category

[(118, 125], (118, 125], (118, 125], (125, 135], (118, 125], ..., (125, 135], (160, 200], (135, 160], (135, 160], (125, 135]]
Length: 12
Categories (4, interval[int64, right]): [(118, 125] < (125, 135] < (135, 160] < (160, 200]]

In [27]:
pd.value_counts(category)

/tmp/ipykernel_471/2654243906.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category)

(118, 125]    5
(125, 135]    3
(135, 160]    3
(160, 200]    1
Name: count, dtype: int64

In [28]:
bin_names = ['Short Height', 'Average height', 'Good Height', 'Taller']
pd.cut(height, bins, labels=bin_names)

['Short Height', 'Short Height', 'Short Height', 'Average height', 'Short Height', ..., 'Average height', 'Taller', 'Good Height', 'Good Height', 'Average height']
Length: 12
Categories (4, object): ['Short Height' < 'Average height' < 'Good Height' < 'Taller']

In [29]:
import numpy as np
#print(np.random.rand(40)) #Random numbers between 0 to 1
pd.cut(np.random.rand(40), 5, precision=2)

[(0.11, 0.28], (0.81, 0.98], (0.28, 0.46], (0.46, 0.63], (0.81, 0.98], ..., (0.63, 0.81], (0.28, 0.46], (0.28, 0.46], (0.63, 0.81], (0.28, 0.46]]
Length: 40
Categories (5, interval[float64, right]): [(0.11, 0.28] < (0.28, 0.46] < (0.46, 0.63] <
                                           (0.63, 0.81] < (0.81, 0.98]]

In [30]:
randomNumbers = np.random.rand(2000)
category3 = pd.qcut(randomNumbers, 4) # cut into quartiles
category3

[(-0.0009578, 0.265], (0.761, 1.0], (0.518, 0.761], (-0.0009578, 0.265], (0.265, 0.518], ..., (0.265, 0.518], (0.518, 0.761], (-0.0009578, 0.265], (0.761, 1.0], (-0.0009578, 0.265]]
Length: 2000
Categories (4, interval[float64, right]): [(-0.0009578, 0.265] < (0.265, 0.518] < (0.518, 0.761] <
                                           (0.761, 1.0]]

In [31]:
pd.value_counts(category3)

/tmp/ipykernel_471/647498483.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category3)

(-0.0009578, 0.265]    500
(0.265, 0.518]         500
(0.518, 0.761]         500
(0.761, 1.0]           500
Name: count, dtype: int64

In [32]:
import pandas as pd
df = pd.read_csv('fraudTrain.csv')
print(df.head())

   Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095
1           1   2019-01-01 00:00:44      630423337322
2           2   2019-01-01 00:00:51    38859492057661
3           3   2019-01-01 00:01:16  3534093764340240
4           4   2019-01-01 00:03:06   375534208663984

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie
2                fraud_Lind-Buckridge  entertainment  220.11     Edward
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629

   city_pop                                job         dob  \
0      3495          Psychologist, counselling  1988-03-09
1       149  Special educational needs teacher  1978-06-21
2      4154        Nature conservation officer  1962-01-19
3      1939                    Patent attorney  1967-01-12
4        99     Dance movement psychotherapist  1986-03-28

                          trans_num   unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315
1  1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462
2  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704 -112.154481
3  6b849c168bdad6f867558c3793159a81  1325376076  47.034331 -112.561071
4  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999  -78.632459

   is_fraud
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0

[5 rows x 23 columns]

In [33]:
df.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0.0
5,5,2019-01-01 00:04:08,4767265376804500,"fraud_Stroman, Hudson and Erdman",gas_transport,94.63,Jennifer,Conner,F,4655 David Island,...,40.3750,-75.2045,2158,Transport planner,1961-06-19,189a841a0a8ba03058526bcfe566aab5,1325376248,40.653382,-76.152667,0.0
6,6,2019-01-01 00:04:42,30074693890476,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,889 Sarah Station Suite 624,...,37.9931,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1325376282,37.162705,-100.153370,0.0
7,7,2019-01-01 00:05:08,6011360759745864,fraud_Corwin-Collins,gas_transport,71.65,Steven,Williams,M,231 Flores Pass Suite 720,...,38.8432,-78.6003,6018,"Designer, multimedia",1947-08-21,6d294ed2cc447d2c71c7171a3d54967c,1325376308,38.948089,-78.540296,0.0
8,8,2019-01-01 00:05:18,4922710831011201,fraud_Herzog Ltd,misc_pos,4.27,Heather,Chase,F,6888 Hicks Stream Suite 954,...,40.3359,-79.6607,1472,Public affairs consultant,1941-03-07,fc28024ce480f8ef21a32d64c93a29f5,1325376318,40.351813,-79.958146,0.0
9,9,2019-01-01 00:06:01,2720830304681674,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,21326 Taylor Squares Suite 708,...,36.5220,-87.3490,151785,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1325376361,37.179198,-87.485381,0.0

In [34]:
amount = pd.to_numeric(df["amt"])
amount[np.abs(amount) > 100]

1         107.23
2         220.11
9         198.39
16        327.00
17        341.67
           ...
968639    244.41
968647    101.43
968656    110.47
968660    506.32
968667    397.04
Name: amt, Length: 175122, dtype: float64

In [35]:
CityPopulation = df["city_pop"]
df[CityPopulation > 2000]

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0.0
5,5,2019-01-01 00:04:08,4767265376804500,"fraud_Stroman, Hudson and Erdman",gas_transport,94.63,Jennifer,Conner,F,4655 David Island,...,40.3750,-75.2045,2158,Transport planner,1961-06-19,189a841a0a8ba03058526bcfe566aab5,1325376248,40.653382,-76.152667,0.0
6,6,2019-01-01 00:04:42,30074693890476,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,889 Sarah Station Suite 624,...,37.9931,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1325376282,37.162705,-100.153370,0.0
7,7,2019-01-01 00:05:08,6011360759745864,fraud_Corwin-Collins,gas_transport,71.65,Steven,Williams,M,231 Flores Pass Suite 720,...,38.8432,-78.6003,6018,"Designer, multimedia",1947-08-21,6d294ed2cc447d2c71c7171a3d54967c,1325376308,38.948089,-78.540296,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968666,968666,2020-01-26 16:29:36,2268221587779419,"fraud_Moore, Williamson and Emmerich",home,31.49,Peggy,Berry,F,517 Vasquez Lodge,...,45.6892,-122.6616,299480,Teaching laboratory technician,1985-01-02,0ed01b2ea7ed09a7d20253187bf433c4,1359217776,45.461769,-121.674844,0.0
968667,968667,2020-01-26 16:30:29,4806443445305,fraud_Mohr Inc,shopping_pos,397.04,Eric,Patel,M,69459 Rachel Prairie Apt. 850,...,38.5294,-82.6654,21635,Geochemist,2001-07-10,0776f9ea5c13369cfcfd2073e0fc2b86,1359217829,38.954684,-82.878929,0.0
968668,968668,2020-01-26 16:31:00,4710792708725663,fraud_Emmerich-Rau,personal_care,9.50,Justin,Bell,M,954 Green Wall,...,41.2290,-85.3244,7692,"Research officer, trade union",1986-12-13,a9dc78fd1606e4f404f55d0b93db5053,1359217860,41.325344,-84.802020,0.0
968670,968670,2020-01-26 16:32:35,3565423334076143,"fraud_Prosacco, Kreiger and Kovacek",home,22.76,Nathan,Thomas,M,4923 Campbell Pines Suite 717,...,38.9763,-87.3667,4081,Energy engineer,1938-03-15,639e6bda10968ab1590fea08f3e7b822,1359217955,39.135523,-87.556171,0.0
968671,968671,2020-01-26 16:32:50,4570636521433188,fraud_Bode-Rempel,kids_pets,77.33,Christine,Leblanc,F,5097 Jodi Vista Suite 811,...,28.8989,-81.2473,88735,Commercial horticulturist,1988-04-09,09b4ac347396104c0a0516d6673d3ae4,1359217970,28.100210,NaN,NaN

In [36]:
Q1 = df['amt'].quantile(0.25)
Q3 = df['amt'].quantile(0.75)
IQR = Q3 - Q1

In [37]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [38]:
print(f"Normal transaction range: ${lower_bound:.2f} to ${upper_bound:.2f}")

Normal transaction range: $-100.49 to $193.19

In [39]:
df_clean = df[(df['amt'] >= lower_bound) & (df['amt'] <= upper_bound)]
df_clean

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0.0
5,5,2019-01-01 00:04:08,4767265376804500,"fraud_Stroman, Hudson and Erdman",gas_transport,94.63,Jennifer,Conner,F,4655 David Island,...,40.3750,-75.2045,2158,Transport planner,1961-06-19,189a841a0a8ba03058526bcfe566aab5,1325376248,40.653382,-76.152667,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968666,968666,2020-01-26 16:29:36,2268221587779419,"fraud_Moore, Williamson and Emmerich",home,31.49,Peggy,Berry,F,517 Vasquez Lodge,...,45.6892,-122.6616,299480,Teaching laboratory technician,1985-01-02,0ed01b2ea7ed09a7d20253187bf433c4,1359217776,45.461769,-121.674844,0.0
968668,968668,2020-01-26 16:31:00,4710792708725663,fraud_Emmerich-Rau,personal_care,9.50,Justin,Bell,M,954 Green Wall,...,41.2290,-85.3244,7692,"Research officer, trade union",1986-12-13,a9dc78fd1606e4f404f55d0b93db5053,1359217860,41.325344,-84.802020,0.0
968669,968669,2020-01-26 16:32:27,6011504998544485,fraud_Rau-Robel,kids_pets,62.61,Ashley,Whitney,F,4038 Smith Avenue,...,32.5104,-86.8138,1089,Materials engineer,1971-11-02,f08b667fe1dd611737ab1bc49ce763dc,1359217947,33.367889,-86.354292,0.0
968670,968670,2020-01-26 16:32:35,3565423334076143,"fraud_Prosacco, Kreiger and Kovacek",home,22.76,Nathan,Thomas,M,4923 Campbell Pines Suite 717,...,38.9763,-87.3667,4081,Energy engineer,1938-03-15,639e6bda10968ab1590fea08f3e7b822,1359217955,39.135523,-87.556171,0.0
968671,968671,2020-01-26 16:32:50,4570636521433188,fraud_Bode-Rempel,kids_pets,77.33,Christine,Leblanc,F,5097 Jodi Vista Suite 811,...,28.8989,-81.2473,88735,Commercial horticulturist,1988-04-09,09b4ac347396104c0a0516d6673d3ae4,1359217970,28.100210,NaN,NaN